In [1]:
from neural_network import NeuralNetwork
from math_functions.loss import LossFunction
from math_functions.activation import ActivationFunction
from monks import read_monk

train_data, train_target = read_monk('datasets/monks/monks-1.train')

In [2]:
train_data.shape, train_target.shape

((124, 17), (124, 1))

In [3]:
train_data[0]

array([1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.])

In [ ]:
nn = NeuralNetwork(1, [3], 1, LossFunction.MSE.value, ActivationFunction.SIGMOID.value, ActivationFunction.SIGMOID.value, 0.5).train(train_data, train_target, 10000, train_data.shape[0])

In [25]:
import numpy as np


a = np.array([1.0000003, 2.00001, 3.0000002])
a_true = np.array([1,2,3])

In [26]:
from math_functions.loss import *

print(mse_prime(a_true, a))
print(mee_prime(a_true, a))


[2.00000000e-07 6.66666667e-06 1.33333333e-07]
[0.02998052 0.99935063 0.01998701]


In [6]:
np.mean(np.sum(a))

6.0

In [3]:
for i in enumerate([1,2,3]):
    print(i)

(0, 1)
(1, 2)
(2, 3)


In [37]:
def discr(x):
    if x - np.floor(x) < 0.5: return np.floor(x)
    else: return np.floor(x) + 1

In [43]:
print(discr(12.39))

12.0
