In [1]:
from neural_network import NeuralNetwork
from math_functions.loss import LossFunction
from math_functions.activation import ActivationFunction
from monks import read_monk

train_data, train_target = read_monk('datasets/monks/monks-1.train')

In [2]:
train_data.shape, train_target.shape

((124, 17), (124, 1))

In [3]:
train_data[0]

array([1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.])

In [ ]:
nn = NeuralNetwork(1, [3], 1, LossFunction.MSE.value, ActivationFunction.SIGMOID.value, ActivationFunction.SIGMOID.value, 0.0001).train(train_data, train_target, 10000, train_data.shape[0])

In [8]:
import numpy as np


a = np.array([[1,2,3],[1,2,3]])


In [9]:
a

array([[1, 2, 3],
       [1, 2, 3]])

In [11]:
np.sum(a, axis=0)

array([2, 4, 6])

In [3]:
for i in enumerate([1,2,3]):
    print(i)

(0, 1)
(1, 2)
(2, 3)
