In [9]:
[x for x in range(10+1)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [12]:
n = np.ndarray((3,2))

In [15]:
n.shape[0]

3

In [28]:
from typing import List
class A:
    def __init__(self):
        self.a: List[int] = list()
        self.a.append(1)
        self.b = None


In [31]:
A().b = 3
print(b)

[1]


In [1]:
from weights_utils import xavier_init
import numpy as np
import importlib
import weights_utils

# Reload the module
importlib.reload(weights_utils)

x = xavier_init(1000, 10)
x.shape

(1000, 10)

In [2]:
np.where(np.logical_or(x > 1/np.sqrt(10), x < -1/np.sqrt(10)))

(array([], dtype=int64), array([], dtype=int64))

In [3]:
from activation_functions import pick_activation, get_name_from_function

pick_activation = activation_functions.pick_activation("relu")
get_name_from_function(pick_activation[1])

'relu_prime'

In [5]:
import numpy as np
a, b = np.ndarray((3,1)), np.ndarray((3,1))
c = np.multiply(a, b)

print(a)
print(b)
print(c)

[[3.]
 [2.]
 [1.]]
[[3.]
 [2.]
 [1.]]
[[9.]
 [4.]
 [1.]]


In [1]:
import math_functions.activation as activation
x = activation.relu(1)

In [4]:
import numpy as np
from math_functions.loss import *

mee_prime(np.array([[1,2,3], [4,5,6]]), np.array([[1,2,3], [11,12,13]]))

array([[-0.        , -0.        , -0.        ],
       [ 0.28867513,  0.28867513,  0.28867513]])

In [4]:
mee_prime(np.array([1,2,3]), np.array([2,3,4]))

array([-0.57735027, -0.57735027, -0.57735027])

In [16]:
a = np.zeros((3,3))
a.shape

(3, 3)

In [17]:
a

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.]])

In [21]:
non_zero = a > 0

In [22]:
non_zero

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [29]:
b = np.zeros_like(a)
b = a[non_zero]

In [30]:
b

array([1.])

In [ ]:
np.fill

In [12]:
a = np.array([1,2,3])
type(a)

numpy.ndarray

In [13]:
a.ndim

1